package thehambone.gtatools.gta3savefileeditor.gui.page;

import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import thehambone.gtatools.gta3savefileeditor.io.IO;
import thehambone.gtatools.gta3savefileeditor.gui.component.cellrenderer.SaveSlotCellRenderer;
import thehambone.gtatools.gta3savefileeditor.savefile.PCSaveSlot;
import thehambone.gtatools.gta3savefileeditor.util.GUIUtils;
import thehambone.gtatools.gta3savefileeditor.util.Logger;

/**
 * @author thehambone
 * @version 0.1
 * @since 0.1, March 30, 2015
 */
public class WelcomePage extends Page
{
    private static final String ICON_PATH = "META-INF/res/logo2.png";
    
    public WelcomePage()
    {
        super("Welcome", Visibility.VISIBLE_WHEN_FILE_NOT_LOADED_ONLY);
        initComponents();
        initListSelectionListener();
        initMouseListener();
    }
    
    private void initListSelectionListener()
    {
        saveSlotList.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e)
            {
                PCSaveSlot saveSlot = (PCSaveSlot)saveSlotList.getSelectedValue();
                if (saveSlot == null) {
                    return;
                }
                
                loadButton.setEnabled(saveSlot.isUsable());
                deleteButton.setEnabled(saveSlot.isUsable());
            }
        });
    }
    
    private void initMouseListener()
    {
        saveSlotList.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                if (e.getButton() == MouseEvent.BUTTON1 && e.getClickCount() == 2 && !saveSlotList.isSelectionEmpty()) {
                    loadSelectedSlot();
                }
            }
        });
    }
    
    @SuppressWarnings("unchecked")
    private void populateSlotList()
    {
        saveSlotList.clearSelection();
        DefaultListModel<PCSaveSlot> saveSlotListModel = new DefaultListModel<>();
        for (PCSaveSlot slot : PCSaveSlot.getSaveSlots()) {
            saveSlotListModel.addElement(slot);
        }
        saveSlotList.setModel(saveSlotListModel);
        saveSlotList.setCellRenderer(new SaveSlotCellRenderer());
        saveSlotList.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        loadButton.setEnabled(!saveSlotList.isSelectionEmpty());
        deleteButton.setEnabled(!saveSlotList.isSelectionEmpty());
        
        saveSlotList.repaint();
    }
    
    private void loadSelectedSlot()
    {
        PCSaveSlot saveSlot = (PCSaveSlot)saveSlotList.getSelectedValue();
        File f = saveSlot.getFile();
        if (saveSlot.isUsable()) {
            return;
        }
        notifyObservers(Event.FILE_LOAD, f);
    }
    
    private void deleteSelectedSlot()
    {
        PCSaveSlot saveSlot = (PCSaveSlot)saveSlotList.getSelectedValue();
        File f = saveSlot.getFile();
        if (saveSlot.isUsable()) {
            return;
        }
        notifyObservers(Event.FILE_DELETE, f);
        if (!f.exists()) {
            GUIUtils.showInformationMessageBox(
                    this, "File deleted successfully!", "Success");
        }
        populateSlotList();
    }
    
    private void refresh()
    {
        notifyObservers(Event.REFRESH_SLOTS);
        populateSlotList();
    }
    
    @Override
    public void loadPage()
    {
        Logger.debug("Loading page: %s...\n", getPageTitle());
        
        try {
            imageLabel.setIcon(new ImageIcon(IO.loadImageResource(ICON_PATH)));
        } catch (IOException ex) {
            Logger.error("Failed to load image resource.");
            Logger.stackTrace(ex);
        }
        imageLabel.setText("");
        refresh();
        populateSlotList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        scrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        loadGamePanel = new javax.swing.JPanel();
        saveSlotScrollPane = new javax.swing.JScrollPane();
        saveSlotList = new javax.swing.JList();
        refreshButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();

        imageLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText("<image>");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loadGamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Load Game"));

        saveSlotList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveSlotList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        saveSlotList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        saveSlotScrollPane.setViewportView(saveSlotList);

        refreshButton.setText("Refresh");
        refreshButton.setToolTipText("");
        refreshButton.setMaximumSize(new java.awt.Dimension(79, 23));
        refreshButton.setMinimumSize(new java.awt.Dimension(79, 23));
        refreshButton.setPreferredSize(new java.awt.Dimension(79, 23));
        refreshButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                refreshButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.setMaximumSize(new java.awt.Dimension(79, 23));
        loadButton.setMinimumSize(new java.awt.Dimension(79, 23));
        loadButton.setPreferredSize(new java.awt.Dimension(79, 23));
        loadButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setMaximumSize(new java.awt.Dimension(79, 23));
        deleteButton.setMinimumSize(new java.awt.Dimension(79, 23));
        deleteButton.setPreferredSize(new java.awt.Dimension(79, 23));
        deleteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteButtonActionPerformed(evt);
            }
        });

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadGamePanelLayout = new javax.swing.GroupLayout(loadGamePanel);
        loadGamePanel.setLayout(loadGamePanelLayout);
        loadGamePanelLayout.setHorizontalGroup(
            loadGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loadGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveSlotScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadGamePanelLayout.createSequentialGroup()
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(browseButton)))
                .addContainerGap())
        );
        loadGamePanelLayout.setVerticalGroup(
            loadGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveSlotScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loadGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_refreshButtonActionPerformed
    {//GEN-HEADEREND:event_refreshButtonActionPerformed
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseButtonActionPerformed
    {//GEN-HEADEREND:event_browseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int option = fileChooser.showOpenDialog(this);
        if (option != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fileChooser.getSelectedFile();
        notifyObservers("load.file", f);
    }//GEN-LAST:event_browseButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadButtonActionPerformed
    {//GEN-HEADEREND:event_loadButtonActionPerformed
        loadSelectedSlot();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteButtonActionPerformed
    {//GEN-HEADEREND:event_deleteButtonActionPerformed
        deleteSelectedSlot();
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton loadButton;
    private javax.swing.JPanel loadGamePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JList saveSlotList;
    private javax.swing.JScrollPane saveSlotScrollPane;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}